spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "1030346179643-gr9fjoshorup5je3cd5felhbfiapqcqa.apps.googleusercontent.com"
            client-secret: "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"
            scope:
              - email
              - profile
jwt:
  issuer: sayingjang@gmail.com
  secret_key: jwt-springboot